DATASET:
    train_list: ['PW3D']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36' 
    workers: 8
    use_gt_input: True   # True vì chúng ta muốn mạng được tiếp xúc nhiều với GT tốt
    seqlen: 16
    stride: 1

MODEL:
    name: 'Teacher'
    hpe_dim: 256
    hpe_dep: 3
    joint_dim: 64
    vertx_dim: 64
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.001
    shape_loss_weight: 0.06
    pose_loss_weight: 0.06
    posenet_pretrained: False

TRAIN:
    print_freq: 20
    batch_size: 16
    shuffle: True
    begin_epoch: 1
    end_epoch: 30
    edge_loss_start: 2
    scheduler: 'step'
    lr: 0.0001
    lr_step: [5, 10, 20]
    lr_factor: 0.5
    optimizer: 'adam'
    wandb: False # Tắt wandb nếu bạn chỉ muốn test nhanh trên máy tính hiện tại

TEST:
    batch_size: 64
    shuffle: False
